### ISSUE TITLE
song progress bar sometimes doesnt update when skipping to a song

### ISSUE THREAD

**Issue by isCamden** [CS499-PlayerPiano/PianoController#10]
????? this happened like once idk why

**Comment by isCamden** [comment]
probably just a local client side issue can be ignored

**Comment by isCamden** [comment]
I found the issue, specifically this happens when you skip towards the end of a song (like in the second half I think)

**Comment by egold555** [comment]
Should be fixed. Need to test with new update

**Comment by egold555** [comment]
Done some testing, forgot to close this.

If it pops up we can investigate more.
