### ISSUE TITLE
some multitrack(?) midis play out of time

### ISSUE THREAD

**Issue by isCamden** [CS499-PlayerPiano/PianoController#16]
- at the speed of light
- around the world
- cruel angel's thesis
- duet
- Etude Op. 10 No. 3 E Major (Tristesse)
- a bunch more I can edit this when I find them

**Comment by isCamden** [comment]
at the speed of light

**Comment by egold555** [comment]
Fix for the issue as of right now: Make each track use a seperate channel.

**Comment by egold555** [comment]
I manaually fixed the DB. Needs a bunch of testing, but its getting late

**Comment by egold555** [comment]
Fur elise is broken. What the ffuucckkkkkk!!!!!!
