### ISSUE TITLE
Scrolling down, selecting a song, then clicking "Back to song list" scrolls back to top

### ISSUE THREAD

**Issue by isCamden** [CS499-PlayerPiano/PianoController#9]
this one isnt a huge deal

**Comment by egold555** [comment]
I added a fix by saving the position in javascript, and then scrolling back to that point.

Probably should be fixed in CSS but I could not figure out how to do that

**Comment by egold555** [comment]
Works on chrome and firefox desktop,

need to test mobile and safari
